// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Area
    {
        public long AreaId { get; set; }
        public string AreaName { get; set; }
        public string Approval { get; set; }
        public DateTime? Mdate { get; set; }
        public string Description { get; set; }
        public long? BranchId { get; set; }
        public long? CreatedBy { get; set; }
        public int? Noofgroup { get; set; }
        public long? ManagerId { get; set; }
        public string Csrapprove { get; set; }
        public DateTime? Mangerdate { get; set; }
        public DateTime? Csrdate { get; set; }
        public long? SurveyInformationId { get; set; }
        public string Fslatitude { get; set; }
        public string Fslongitude { get; set; }
        public byte[] Fspic { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public long? OriginatorId { get; set; }
        public DateTime? OfficerChangeDate { get; set; }
        public string OtpBlc { get; set; }
        public string VerifyOtpBlc { get; set; }
        public string Dveapproval { get; set; }
        public DateTime? DveapprovalDateTime { get; set; }
        public bool? IsTopupLoan { get; set; }
        public long? ExistingCenterId { get; set; }
    }
}