// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class AreaTransferredToTe
    {
        public DateTime Createddate { get; set; }
        public long AssignedBy { get; set; }
        public long OldFieldOfficerId { get; set; }
        public long NewFieldOfficer { get; set; }
        public long SurveyInformationId { get; set; }
    }
}