// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class AssignBranch
    {
        public long AssignBrMapid { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public long RoleId { get; set; }
        public long? CreatedBy { get; set; }
    }
}