// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class AssignSurvey
    {
        public long AssignSurveyId { get; set; }
        public string AreaName { get; set; }
        public string AreaLatitude { get; set; }
        public string AreaLongitude { get; set; }
        public long BranchId { get; set; }
        public long AssignUserId { get; set; }
        public long AssignedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool? IsSurveyDone { get; set; }
    }
}