// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class BranchTarget
    {
        public long Branchtargetid { get; set; }
        public double DisburssementAmount { get; set; }
        public int NoofAccounttoopen { get; set; }
        public DateTime AssignMonth { get; set; }
        public long BranchId { get; set; }
        public long Assignby { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}