// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Branch
    {
        public long BranchId { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string BranchCity { get; set; }
        public string BranchState { get; set; }
        public string BranchCode { get; set; }
        public DateTime? Bdate { get; set; }
        public bool? Active { get; set; }
        public string LatLong { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}