// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Branding
    {
        public long Id { get; set; }
        public string AreaName { get; set; }
        public string SubAreaName { get; set; }
        public string ScheduledDate { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string MeetingStatus { get; set; }
        public string Remark { get; set; }
        public string MeetingCompletedDt { get; set; }
        public int? CompletedBy { get; set; }
        public int? RescheduledTimes { get; set; }
        public string OriginalScheduledDate { get; set; }
        public int? NoOfProspects { get; set; }
        public string Deliverables { get; set; }
        public byte[] Photo { get; set; }
        public string MeetingType { get; set; }
        public string ScheduledTime { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}