// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class CashFlowBusiness
    {
        public int Id { get; set; }
        public decimal? IncomingCash { get; set; }
        public decimal? IncomingSales { get; set; }
        public decimal? IncomingReceivables { get; set; }
        public decimal? OtherIncome { get; set; }
        public decimal? TotalIncome { get; set; }
        public decimal? LoanEmi { get; set; }
        public decimal? Rent { get; set; }
        public decimal? MaterialPurchase { get; set; }
        public decimal? SalariesAndWages { get; set; }
        public decimal? MarketingExp { get; set; }
        public decimal? PhoneBills { get; set; }
        public decimal? Internet { get; set; }
        public decimal? ElectricityBill { get; set; }
        public decimal? MotorFuelExpenses { get; set; }
        public decimal? TransportationExpenses { get; set; }
        public decimal? MotorMaintenanceExp { get; set; }
        public decimal? Insurance { get; set; }
        public decimal? Taxes { get; set; }
        public decimal? Utility { get; set; }
        public decimal? GeneralAndAdministrative { get; set; }
        public decimal? MedicalExp { get; set; }
        public decimal? MiscellaneousExp { get; set; }
        public long CustomerId { get; set; }
        public decimal? TotalOutgoing { get; set; }

        public virtual Customer Customer { get; set; }
    }
}