// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class CashFlowSalary
    {
        public int Id { get; set; }
        public long CustomerId { get; set; }
        public decimal? MonthlyIncome { get; set; }
        public decimal? SpouseIncome { get; set; }
        public decimal? OtherFamilyMemberIncome { get; set; }
        public decimal? OtherIncome { get; set; }
        public decimal? TotalIncome { get; set; }
        public decimal? LoanEmi { get; set; }
        public decimal? Rent { get; set; }
        public decimal? EducationalFees { get; set; }
        public decimal? TutionFees { get; set; }
        public decimal? PersonalInsurance { get; set; }
        public decimal? PropertyTax { get; set; }
        public decimal? Sip { get; set; }
        public decimal? PhoneBill { get; set; }
        public decimal? Internet { get; set; }
        public decimal? ElectricityBill { get; set; }
        public decimal? Dth { get; set; }
        public decimal? GroceryAndVegetable { get; set; }
        public decimal? Milk { get; set; }
        public decimal? CookingGas { get; set; }
        public decimal? Maid { get; set; }
        public decimal? CarInsurance { get; set; }
        public decimal? Fuel { get; set; }
        public decimal? VehicleMaintenance { get; set; }
        public decimal? MedicalExpenses { get; set; }
        public decimal? FunctionCelebration { get; set; }
        public decimal? OtherExpenses { get; set; }
        public decimal? TotalOutgoing { get; set; }

        public virtual Customer Customer { get; set; }
    }
}