// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class CashFlow
    {
        public long CashflowId { get; set; }
        public long CustomerId { get; set; }
        public double? OpeningBalance { get; set; }
        public double? Cashincoming { get; set; }
        public double Sales { get; set; }
        public double? Assetsales { get; set; }
        public double? Debtorreceipts { get; set; }
        public double? Otherincome { get; set; }
        public double? Totalincoming { get; set; }
        public double? Cashoutgoing { get; set; }
        public double Purchases { get; set; }
        public double? Accountantfees { get; set; }
        public double? Solicitorfees { get; set; }
        public double? Advertisingandmarketing { get; set; }
        public double? Bankfeesandcharges { get; set; }
        public double? Interestpaid { get; set; }
        public double? Creditcardfees { get; set; }
        public double? Utilities { get; set; }
        public double? Telephone { get; set; }
        public double? Leaseorloanpayments { get; set; }
        public double? Rentandrates { get; set; }
        public double? Motorvehicleexpenses { get; set; }
        public double? Repairsandmaintenance { get; set; }
        public double? Stationeryandprinting { get; set; }
        public double? Licensing { get; set; }
        public double? Insurance { get; set; }
        public double? Incometax { get; set; }
        public double? Wages { get; set; }
        public double? Totaloutgoing { get; set; }
        public double? Closingbalance { get; set; }
        public double? FamilyIncome { get; set; }
        public bool? IsTopupLoan { get; set; }
        public double? LoanEmi { get; set; }
        public double? Rent { get; set; }
        public double? MaterialPurchase { get; set; }
        public double? MarketingExp { get; set; }
        public double? Interest { get; set; }
        public double? ElectricityBill { get; set; }
        public double? MotorFuelExpenses { get; set; }
        public double? TransportationExpenses { get; set; }
        public double? GeneralAdministrative { get; set; }
        public double? MedicalExp { get; set; }
        public double? MiscellaneousExp { get; set; }
        public double? MonthlyIncome { get; set; }
        public double? SpouseIncome { get; set; }
        public double? OtherFamilyMemberIncome { get; set; }
        public double? EducationalFees { get; set; }
        public double? TutionFees { get; set; }
        public double? PersonalInsurance { get; set; }
        public double? PropertyTax { get; set; }
        public double? Sip { get; set; }
        public double? PhoneBill { get; set; }
        public double? Internet { get; set; }
        public double? Dth { get; set; }
        public double? GroceryVegetables { get; set; }
        public double? Milk { get; set; }
        public double? CookingGas { get; set; }
        public double? Fuel { get; set; }
        public double? VehicalMaintenance { get; set; }
        public double? FunctionCelebration { get; set; }
        public double? OtherExp { get; set; }
    }
}