// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Cgroup
    {
        public long GroupId { get; set; }
        public string GroupName { get; set; }
        public string Contactno { get; set; }
        public string ContactPerson { get; set; }
        public int? CurrentNoofMember { get; set; }
        public int? MemberLimitId { get; set; }
        public string PanCardNumber { get; set; }
        public long? BranchId { get; set; }
        public DateTime? Groupdate { get; set; }
        public long? CreatedBy { get; set; }
        public long? LastModifiedby { get; set; }
        public string Approval { get; set; }
        public long? AreaId { get; set; }
        public long? ManagerId { get; set; }
        public string Csrapprove { get; set; }
        public DateTime? Mangerdate { get; set; }
        public DateTime? Csrdate { get; set; }
        public long? OriginatorId { get; set; }
        public DateTime? OfficerChangeDate { get; set; }
        public long? Otp { get; set; }
        public long? VerifyOtp { get; set; }
        public string DvegroupApproval { get; set; }
        public DateTime? DvegroupApprovalDateTime { get; set; }
        public bool? IsTopupLoan { get; set; }
        public long? ExistingGroupId { get; set; }
        public long? ExistingCenterId { get; set; }
    }
}