// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class ChangeOfficerLog
    {
        public long ChangeOfficerLogId { get; set; }
        public long? OldFieldOfficer { get; set; }
        public long? NewFieldOfficer { get; set; }
        public DateTime? ChangeDate { get; set; }
        public long? BranchId { get; set; }
    }
}