// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class CompanySetup
    {
        public long CompanySetupId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string Registrationno { get; set; }
        public long? Phoneno { get; set; }
        public byte[] Companylogo { get; set; }
        public string CompanyNameEnglish { get; set; }
    }
}