// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class CustomerDetails
    {
        public long Cdid { get; set; }
        public string BeniBankName { get; set; }
        public string BeniBranchName { get; set; }
        public string BeniIfscCode { get; set; }
        public string BeniAccountNo { get; set; }
        public string BeniName { get; set; }
        public string BeniAddress { get; set; }
        public long? CustomerId { get; set; }
    }
}