// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Day
    {
        public Day()
        {
            GroupTrainingProcess = new HashSet<GroupTrainingProcess>();
        }

        public int DaysId { get; set; }
        public string DayName { get; set; }
        public string Statement { get; set; }
        public long? Createdby { get; set; }
        public DateTime DateCreated { get; set; }
        public int? ProcessId { get; set; }
        public int? DaySequence { get; set; }

        public virtual ICollection<GroupTrainingProcess> GroupTrainingProcess { get; set; }
    }
}