// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Emiinstallments
    {
        public int Id { get; set; }
        public int InstallmentNo { get; set; }
        public string DateOfEmi { get; set; }
        public decimal? PrincipalOutstanding { get; set; }
        public decimal? Emi { get; set; }
        public decimal? Principal { get; set; }
        public decimal? Interest { get; set; }
        public decimal? Outstanding { get; set; }
        public int? CustomerId { get; set; }
        public int? DisbursementId { get; set; }
    }
}