// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class FaceTagging
    {
        public int FaceTaggingId { get; set; }
        public int BranchId { get; set; }
        public int AreaId { get; set; }
        public int GroupId { get; set; }
        public int CustomerId { get; set; }
        public byte[] Cgt1taggedPhoto { get; set; }
        public byte[] Cgt2taggedPhoto { get; set; }
        public byte[] FsappraisalPhoto { get; set; }
        public double? Cgt1matchPercentage { get; set; }
        public double? Cgt2matchPercentage { get; set; }
        public double? FsappraisalMatchPercentage { get; set; }
        public int FsfaceTaggingStatus { get; set; }
        public string CreationDateTime { get; set; }
        public string FsappraisalDateTime { get; set; }
    }
}