// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class getAssignedAreasResult
    {
        public string AreaName { get; set; }
        public long SurveyInformationid { get; set; }
        public long UserId { get; set; }
    }
}
