// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class GlinstallmentOtp
    {
        public long InstallmentId { get; set; }
        public long GroupId { get; set; }
        public long AreaId { get; set; }
        public long BranchId { get; set; }
        public string Otp { get; set; }
        public string VerifyOtp { get; set; }
        public DateTime InstallmentDate { get; set; }
        public int? InstallmentNo { get; set; }
        public bool? IsMsgSent { get; set; }
    }
}