// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class ImportwithAccount
    {
        public double? CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string BranchName { get; set; }
        public string CenterName { get; set; }
        public double? GroupId { get; set; }
        public double? Csrcode { get; set; }
        public double? LoanAmount { get; set; }
        public double? ProductCode { get; set; }
        public string LoanCycleNo { get; set; }
        public string MartialStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpouseDob { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAge { get; set; }
        public string NomineeRelation { get; set; }
        public double? MobileNo { get; set; }
        public double? AccountNo { get; set; }
        public double? SavingaccountNo { get; set; }
        public double? VerifyAccountNo { get; set; }
        public double? VerifySavingaccountNo { get; set; }
    }
}