// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LoanApplication
    {
        public long LoanApplicationId { get; set; }
        public long? LoanTypeid { get; set; }
        public double ExpectedLoanAmount { get; set; }
        public string PurposeofLoan { get; set; }
        public long? CreatedBy { get; set; }
        public long? BranchId { get; set; }
        public DateTime? ApplyDate { get; set; }
        public string ApplicationStatus { get; set; }
    }
}