// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LoanAccount
    {
        public long LoanId { get; set; }
        public long? AccountNo { get; set; }
        public long? CustomerId { get; set; }
        public double? Amount { get; set; }
        public double? Interestrate { get; set; }
        public int? Durationinmonth { get; set; }
        public long? LoanTypeid { get; set; }
        public double? TotalAmount { get; set; }
        public double? Balance { get; set; }
        public double? Installmentamount { get; set; }
        public int? NoofInstallments { get; set; }
        public DateTime? Accountdate { get; set; }
        public DateTime? FirstInstallmentDate { get; set; }
        public string Status { get; set; }
        public bool? AccountVerification { get; set; }
        public double? OdinterestAmount { get; set; }
        public string InterestType { get; set; }
    }
}