// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LoanApplicant
    {
        public long LoanApplicantId { get; set; }
        public string FullName { get; set; }
        public DateTime DateofBirth { get; set; }
        public string CountryOfBirth { get; set; }
        public string PanCardNo { get; set; }
        public string MartialStatus { get; set; }
        public string Education { get; set; }
        public string Gender { get; set; }
        public string CurrentAddr { get; set; }
        public string PermanentAddr { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Yearcurrentaddr { get; set; }
        public string Currentresidencestatus { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string Religion { get; set; }
        public string Category { get; set; }
        public string Occupation { get; set; }
        public long LoanApplicationId { get; set; }
        public string NameofCompany { get; set; }
        public string Designation { get; set; }
        public string OfficeAddress { get; set; }
        public string Officecity { get; set; }
        public long? Officepincode { get; set; }
        public long? Respincode { get; set; }
        public string OfficeState { get; set; }
        public string EmployeeNo { get; set; }
        public byte[] ApplicantImage { get; set; }
        public string EmailId { get; set; }
        public string PhotoIdentityType { get; set; }
        public string PhotoIdentityNumber { get; set; }
        public long? Createdby { get; set; }
        public long? BranchId { get; set; }
        public DateTime? ApplyDate { get; set; }
        public byte[] Icardphoto { get; set; }
        public byte[] ApplicantPhoto { get; set; }
    }
}