// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LoanType
    {
        public long LoanTypeid { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public double? InterestRate { get; set; }
        public int? Durationinmonth { get; set; }
        public double? Amount { get; set; }
        public int? NoofInstallments { get; set; }
        public bool? Active { get; set; }
        public string InterestType { get; set; }
        public string InstallMentFrequency { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}