// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LoanTransaction
    {
        public LoanTransaction()
        {
            SavingTransaction = new HashSet<SavingTransaction>();
        }

        public long LoanTransactionId { get; set; }
        public long CustomerId { get; set; }
        public double Amount { get; set; }
        public DateTime Depositdate { get; set; }
        public double? Balance { get; set; }
        public string TransactionType { get; set; }
        public string Chequeno { get; set; }
        public string BankName { get; set; }
        public string Remark { get; set; }
        public double? Principal { get; set; }
        public double? Interestamount { get; set; }
        public long? AccountNo { get; set; }
        public long? CreatedBy { get; set; }
        public string Status { get; set; }
        public double? OdinterestAmount { get; set; }
        public double? Odprinciple { get; set; }
        public double? Odinterest { get; set; }

        public virtual ICollection<SavingTransaction> SavingTransaction { get; set; }
    }
}