// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Log
    {
        public long Logid { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public DateTime? TimeStamp { get; set; }
        public long? CreatedBy { get; set; }
    }
}