// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class LogTransaction
    {
        public long Id { get; set; }
        public long? LoanTransactionId { get; set; }
        public long? CustomerId { get; set; }
        public decimal? Pbalance { get; set; }
        public decimal? Pprinciple { get; set; }
        public decimal? Pinterest { get; set; }
        public decimal? Nbalance { get; set; }
        public decimal? Nprinciple { get; set; }
        public decimal? Ninterest { get; set; }
        public DateTime? DepositDate { get; set; }
        public decimal? Installment { get; set; }
    }
}