// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Mbb
    {
        public long Mbbid { get; set; }
        public string AreaName { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public string Frequency { get; set; }
        public string Pincode { get; set; }
        public string Details { get; set; }
        public string LatLong { get; set; }
        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }
        public string ExtraField3 { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDatetime { get; set; }
    }
}