// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Mbbattendance
    {
        public long MbbattendanceId { get; set; }
        public string AreaName { get; set; }
        public string Mbbname { get; set; }
        public long? Mbbid { get; set; }
        public DateTime? AttendanceDateTime { get; set; }
        public long? UserId { get; set; }
        public string LatLong { get; set; }
    }
}