// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class MeetingParticipants
    {
        public int Id { get; set; }
        public string ParticipantName { get; set; }
        public string ParticipantNumber { get; set; }
        public int BrandingId { get; set; }
        public string AddedAt { get; set; }
        public DateTime? CreationTime { get; set; }
    }
}