// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class MemberLimit
    {
        public int MemberLimitId { get; set; }
        public string Description { get; set; }
        public int NoofMember { get; set; }
    }
}