// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Question
    {
        public long QuestionId { get; set; }
        public string QuestionDescription { get; set; }
        public int DaysId { get; set; }
        public long? Createdby { get; set; }
        public DateTime? DateCreated { get; set; }
    }
}