// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class SavingTransaction
    {
        public long SavingTransactionId { get; set; }
        public long CustomerId { get; set; }
        public double SavingAmount { get; set; }
        public DateTime Depositdate { get; set; }
        public double? Balance { get; set; }
        public string TransactionType { get; set; }
        public string Chequeno { get; set; }
        public string BankName { get; set; }
        public string Remark { get; set; }
        public long? AccountNo { get; set; }
        public long? CreatedBy { get; set; }
        public string Status { get; set; }
        public long? LoanTransactionId { get; set; }

        public virtual LoanTransaction LoanTransaction { get; set; }
    }
}