// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class SecurityAnswers
    {
        public long AnswerId { get; set; }
        public long? QuestionId { get; set; }
        public string Answer { get; set; }
        public long? UserId { get; set; }
        public long? CustomerId { get; set; }
        public string Question { get; set; }
        public DateTime? LastModifiedDateTime { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual SecurityQuestions QuestionNavigation { get; set; }
        public virtual UserInfo User { get; set; }
    }
}