// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Sms
    {
        public int Smsid { get; set; }
        public string Gatewayurl { get; set; }
        public string Username { get; set; }
        public string Apikey { get; set; }
        public string Senderid { get; set; }
    }
}