// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class sp_GetTrainingTestResult
    {
        public long TestID { get; set; }
        public string TestName { get; set; }
        public string TestURL { get; set; }
        public long? RoleID { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public long? Active { get; set; }
    }
}
