// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class sp_getPendencyReportResult
    {
        public int? NO_OF_CGT1 { get; set; }
        public int? No_of_CGT1_Customers { get; set; }
        public int? NO_OF_CGT2 { get; set; }
        public int? No_of_CGT2_Customers { get; set; }
        public int? No_OF_Branding { get; set; }
        public int? No_OF_Branding_Customers { get; set; }
        public int? No_of_CM { get; set; }
        public int? No_OF_CM_Customers { get; set; }
    }
}
