// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class spI_TrainingAnswersResult
    {
        [Column(TypeName = "decimal(38,0)")]
        public decimal? RETURNVAL { get; set; }
    }
}
