// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class spI_GetODReportResult
    {
        public string report_date { get; set; }
        public string branch_code { get; set; }
        public string BranchName { get; set; }
        public long? product_code { get; set; }
        public long? AreaId { get; set; }
        public string AreaName { get; set; }
        public long? CenterId { get; set; }
        public string CenterName { get; set; }
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public long? GroupId { get; set; }
        public string GroupName { get; set; }
        public long? AccountNo { get; set; }
        public long? SavingaccountNo { get; set; }
        public string LoanCycleNo { get; set; }
        public string MartialStatus { get; set; }
        public string SpouseName { get; set; }
        public DateTime? SpouseDOB { get; set; }
        public int? SpouseAge { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAge { get; set; }
        public string NomineeRelation { get; set; }
        public string LoanPurpose { get; set; }
        public string MobileNo { get; set; }
        public string Collector { get; set; }
        public long CollectorId { get; set; }
        public string OriginatorName { get; set; }
        public long? OriginatorId { get; set; }
        public string DisburseDate { get; set; }
        public string Startdate { get; set; }
        public string MaturityDate { get; set; }
        public double? loanAmount { get; set; }
        public int? NoofInstallments { get; set; }
        public double? EmiAmount { get; set; }
        public string WelfareCharges { get; set; }
        public double? interestrate { get; set; }
        public double? Balance { get; set; }
        public double? AmountTobeCollectedTillNow { get; set; }
        public double? TotalCollected { get; set; }
        public double? Balancebeforematurity { get; set; }
        public double? OverdueAmount { get; set; }
        public double? OverdueInterestAmount { get; set; }
        public double? PendingInstallment { get; set; }
        public double? AftermaturityDateReceived { get; set; }
        public int? overduedays { get; set; }
        public int? OverdueMaturityDays { get; set; }
        public DateTime? LastDepositDate { get; set; }
    }
}
