// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class spI_syncDataByBEResult
    {
        public string AreaName { get; set; }
        public long? BranchId { get; set; }
        public long UserId { get; set; }
        public string FOLatitude { get; set; }
        public string FOLongitude { get; set; }
    }
}
