// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CapMobileWebApp.DAL.Model
{
    public partial class spS_ValidateLoginResult
    {
        public long UserId { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public long? BranchId { get; set; }
        public string Username { get; set; }
        public string Apassword { get; set; }
        public string BranchName { get; set; }
        public string LatLong { get; set; }
        public int? TestAvailableCount { get; set; }
    }
}
