// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class SubmittedCollectionAmount
    {
        public long Id { get; set; }
        public decimal? Amount { get; set; }
        public byte[] AmountReceipt { get; set; }
        public long? Teid { get; set; }
        public long? CreatedBy { get; set; }
        public string CentersList { get; set; }
        public string CustomerList { get; set; }
        public DateTime CreationDate { get; set; }
    }
}