// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Survey
    {
        public long SurveyId { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
        public string OpinionKeyperson { get; set; }
        public string OpinionCsr { get; set; }
        public string ManagerApprove { get; set; }
        public string Csrapprove { get; set; }
        public long CreatedBy { get; set; }
        public long BranchId { get; set; }
        public DateTime SurveyDate { get; set; }
    }
}