// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class SurveyInfo
    {
        public double Totalhouse { get; set; }
        public double? Schouse { get; set; }
        public double? Sthouse { get; set; }
        public double? Minorityhouse { get; set; }
        public double? Obchouse { get; set; }
        public double TotalArea { get; set; }
        public double? WaterReservior { get; set; }
        public double? Rainfed { get; set; }
        public double? ForestLand { get; set; }
        public double? Irrigated { get; set; }
        public int? Hotel { get; set; }
        public int? TeaShop { get; set; }
        public int? Kirana { get; set; }
        public int? TailoringShop { get; set; }
        public int? CycleShop { get; set; }
        public int? Electricalrepairandservice { get; set; }
        public int? Utensil { get; set; }
        public int? AgriinputShop { get; set; }
        public int? Agriprocessingunits { get; set; }
        public int? Panshop { get; set; }
        public int? Others { get; set; }
        public string BusService { get; set; }
        public string AutoService { get; set; }
        public string Qualityofroad { get; set; }
        public double? PrimarySchooldistance { get; set; }
        public string PoliceStation { get; set; }
        public string PrimaryHealthCareCenter { get; set; }
        public string PrimarySchool { get; set; }
        public string Market { get; set; }
        public int? DairySociety { get; set; }
        public int? DairySocietyClients { get; set; }
        public int? FarmerClub { get; set; }
        public int? FarmerClubClients { get; set; }
        public int? Shgs { get; set; }
        public int? ShgsClients { get; set; }
        public int? CooperativeCreditsociety { get; set; }
        public int? CooperativeCreditsocietyclient { get; set; }
        public int? Cooperativebankbranch { get; set; }
        public int? Cooperativebankbranchclient { get; set; }
        public int? Grameenbankbranch { get; set; }
        public int? Grameenbankbranchclient { get; set; }
        public int? Commercialbankbranch { get; set; }
        public int? Commercialbankbranchclient { get; set; }
        public string Mfis1Name { get; set; }
        public int? Mfis1Number { get; set; }
        public int? Mfis1Client { get; set; }
        public string Mfis2Name { get; set; }
        public int? Mfis2Number { get; set; }
        public int? Mfis2Client { get; set; }
        public string Mfis3Name { get; set; }
        public int? Mfis3Number { get; set; }
        public int? Mfis3Client { get; set; }
        public string Mfis4Name { get; set; }
        public int? Mfis4Number { get; set; }
        public int? Mfis4Client { get; set; }
        public string Crop1Name { get; set; }
        public double? Crop1AcresunderCultivation { get; set; }
        public double? Crop1peracreyieldinkg { get; set; }
        public string Crop2Name { get; set; }
        public double? Crop2AcresunderCultivation { get; set; }
        public double? Crop2peracreyieldinkg { get; set; }
        public string Crop3Name { get; set; }
        public double? Crop3AcresunderCultivation { get; set; }
        public double? Crop3peracreyieldinkg { get; set; }
        public string Crop4Name { get; set; }
        public double? Crop4AcresunderCultivation { get; set; }
        public double? Crop4peracreyieldinkg { get; set; }
        public long? CreatedBy { get; set; }
        public long? BranchId { get; set; }
        public DateTime? SurveyDate { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
    }
}