// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class TrainingAnswers
    {
        public long TrainingAnswerId { get; set; }
        public long TrainingReportId { get; set; }
        public long TrainingQuestionId { get; set; }
        public int SelectedAnswer { get; set; }
    }
}