// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class TrainingReport
    {
        public int TrainingReportId { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public DateTime TestDateTime { get; set; }
        public string Result { get; set; }
        public double Marks { get; set; }
    }
}