// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class TrainingQuestions
    {
        public long TrainingQuestionId { get; set; }
        public string TrainingQuestion { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Answer { get; set; }
        public long? TestId { get; set; }

        public virtual TrainingTest Test { get; set; }
    }
}