// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class TrainingTest
    {
        public TrainingTest()
        {
            TrainingQuestions = new HashSet<TrainingQuestions>();
        }

        public long TestId { get; set; }
        public string TestName { get; set; }
        public string TestUrl { get; set; }
        public long? RoleId { get; set; }
        public long? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public long? Active { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<TrainingQuestions> TrainingQuestions { get; set; }
    }
}