// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class UserInfo
    {
        public UserInfo()
        {
            SecurityAnswers = new HashSet<SecurityAnswers>();
        }

        public long UserId { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string Username { get; set; }
        public string Apassword { get; set; }
        public long RoleId { get; set; }
        public byte[] Userimage { get; set; }
        public long? BranchId { get; set; }
        public bool? Active { get; set; }
        public long? UnderofId { get; set; }
        public string EmpCode { get; set; }
        public string UserMobileNo { get; set; }
        public long? AssociatedBeid { get; set; }

        public virtual ICollection<SecurityAnswers> SecurityAnswers { get; set; }
    }
}