// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class UserTarget
    {
        public long Usertargetid { get; set; }
        public double DisburssementAmount { get; set; }
        public int NoofAccounttoopen { get; set; }
        public DateTime AssignMonth { get; set; }
        public long BranchId { get; set; }
        public long AssignedUser { get; set; }
        public long AssignedBy { get; set; }
        public DateTime? Createddate { get; set; }
    }
}